<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="11.00" os="Windows XP" host="TY-GH"><DocLocation><![CDATA[C:\Program Files\HP\QuickTest Professional\Tests\Sumitomo\Script\Case4_2_VehiMsg_MsgQuery_Log]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Case4_2_VehiMsg_MsgQuery_Log]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Action1 [CleanHistoryData]]]></AName>
<Step rID="T6">
<Obj ><![CDATA[日志对应设备autotest历史数据清除完毕]]></Obj>
<Details ><![CDATA[日志对应设备autotest历史数据清除完毕]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:56]]></Time>
<TimeTick>1407922196</TimeTick>
<NodeArgs eType="User" icon="6" nRep="9" status="Passed" Source="Action1 [CleanHistoryData]" SourceLine="46" >
<Disp><![CDATA[日志对应设备autotest历史数据清除完毕]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2014-8-13 - 17:29:55" eTime="2014-8-13 - 17:29:56" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[Action1 [CleanHistoryData] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T7">
<AName><![CDATA[Action1 [Login]]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:56]]></Time>
<TimeTick>1407922196</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:56]]></Time>
<TimeTick>1407922196</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" status="Passed" Source="Action1 [Login]" SourceLine="5" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="14" status="Passed" Source="Action1 [Login]" SourceLine="5" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[住友]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[登录页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[帐户.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="19" Source="Action1 [Login]" SourceLine="7" >
<Disp><![CDATA[帐户.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="18" Source="Action1 [Login]" SourceLine="7" >
<Disp><![CDATA[登录页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="17" Source="Action1 [Login]" SourceLine="7" >
<Disp><![CDATA[住友]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;LockUnlockFlag&gt; column does not exist.<BR>Line (10): &quot;if(Datatable(&quot;LockUnlockFlag&quot;,&quot;Global&quot;)=&quot;锁车&quot;)then&quot;. ]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="20" status="Failed" Source="Action1 [Login]" SourceLine="9" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[住友]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[登录页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[帐户.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["AutoProdtest"]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="Action1 [Login]" SourceLine="9" >
<Disp><![CDATA[帐户.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[密码.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" Source="Action1 [Login]" SourceLine="15" >
<Disp><![CDATA[密码.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[密码.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123"]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="30" Source="Action1 [Login]" SourceLine="16" >
<Disp><![CDATA[密码.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[登录.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="32" Source="Action1 [Login]" SourceLine="18" >
<Disp><![CDATA[登录.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:29:59]]></Time>
<TimeTick>1407922199</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="35" Source="Action1 [Login]" SourceLine="19" >
<Disp><![CDATA[登录.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="24" Source="Action1 [Login]" SourceLine="9" >
<Disp><![CDATA[登录页]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[主页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:00]]></Time>
<TimeTick>1407922200</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[主页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:00]]></Time>
<TimeTick>1407922200</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" Source="Action1 [Login]" SourceLine="22" >
<Disp><![CDATA[主页.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="38" Source="Action1 [Login]" SourceLine="22" >
<Disp><![CDATA[主页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="23" Source="Action1 [Login]" SourceLine="9" >
<Disp><![CDATA[住友]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;LockUnlockFlag&gt; column does not exist.<BR>Line (28): &quot;if(Datatable(&quot;LockUnlockFlag&quot;,&quot;Global&quot;)=&quot;锁车&quot;)then&quot;. ]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:00]]></Time>
<TimeTick>1407922200</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="41" status="Failed" Source="Action1 [Login]" SourceLine="27" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[二次登录成功]]></Obj>
<Details ><![CDATA[期望登录用户名: AutoProdtest实际登录用户名是: AutoProdtest]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:00]]></Time>
<TimeTick>1407922200</TimeTick>
<NodeArgs eType="User" icon="6" nRep="42" status="Passed" Source="Action1 [Login]" SourceLine="29" >
<Disp><![CDATA[二次登录成功]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2014-8-13 - 17:29:56" eTime="2014-8-13 - 17:30:00" passed="2" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="11" status="Failed" >
<Disp><![CDATA[Action1 [Login] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T25">
<AName><![CDATA[Action1 [IntoVehiInfoFramePage]]]></AName>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[住友]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:01]]></Time>
<TimeTick>1407922201</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[主页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:01]]></Time>
<TimeTick>1407922201</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[左导航栏]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:01]]></Time>
<TimeTick>1407922201</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[查询中心.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:01]]></Time>
<TimeTick>1407922201</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="49" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="3" >
<Disp><![CDATA[查询中心.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[查询中心.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:01]]></Time>
<TimeTick>1407922201</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="52" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="4" >
<Disp><![CDATA[查询中心.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="48" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="3" >
<Disp><![CDATA[左导航栏]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="47" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="3" >
<Disp><![CDATA[主页]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[主页_查询中心]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:01]]></Time>
<TimeTick>1407922201</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[查询中心]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:01]]></Time>
<TimeTick>1407922201</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[位置:查询中心.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:01]]></Time>
<TimeTick>1407922201</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="56" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="8" >
<Disp><![CDATA[位置:查询中心.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="55" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="8" >
<Disp><![CDATA[查询中心]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="54" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="8" >
<Disp><![CDATA[主页_查询中心]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="46" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="3" >
<Disp><![CDATA[住友]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[进入查询中心页成功]]></Obj>
<Details ><![CDATA[期望位置:您的位置：>> 查询中心  实际位置:您的位置：>> 查询中心]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:02]]></Time>
<TimeTick>1407922202</TimeTick>
<NodeArgs eType="User" icon="6" nRep="58" status="Passed" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="11" >
<Disp><![CDATA[进入查询中心页成功]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[住友]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:02]]></Time>
<TimeTick>1407922202</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[主页_查询中心]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:02]]></Time>
<TimeTick>1407922202</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[查询中心]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:02]]></Time>
<TimeTick>1407922202</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[机号.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:02]]></Time>
<TimeTick>1407922202</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="63" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="17" >
<Disp><![CDATA[机号.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[机号.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["autotest"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:02]]></Time>
<TimeTick>1407922202</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="66" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="18" >
<Disp><![CDATA[机号.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[唯一查询.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:02]]></Time>
<TimeTick>1407922202</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="68" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="20" >
<Disp><![CDATA[唯一查询.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[唯一查询.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:02]]></Time>
<TimeTick>1407922202</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="71" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="21" >
<Disp><![CDATA[唯一查询.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="62" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="17" >
<Disp><![CDATA[查询中心]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="61" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="17" >
<Disp><![CDATA[主页_查询中心]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[主页_车辆信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:03]]></Time>
<TimeTick>1407922203</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["您的位置>>车辆信息"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>innertext=您的位置：&gt&gt 车辆信息<br>html tag=TD<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (180 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=TD<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 145 matches)</SPAN><br>class=weizhi<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>innertext=您的位置：&gt&gt 车辆信息<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:03]]></Time>
<TimeTick>1407922203</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="74" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="25" >
<Disp><![CDATA["您的位置>>车辆信息"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[您的位置>>车辆信息.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:03]]></Time>
<TimeTick>1407922203</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="75" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="25" >
<Disp><![CDATA[您的位置>>车辆信息.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA["您的位置>>车辆信息"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>innertext=您的位置：&gt&gt 车辆信息<br>html tag=TD<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (180 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=TD<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 145 matches)</SPAN><br>class=weizhi<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>innertext=您的位置：&gt&gt 车辆信息<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>visible=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:03]]></Time>
<TimeTick>1407922203</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="77" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="26" >
<Disp><![CDATA["您的位置>>车辆信息"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="73" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="25" >
<Disp><![CDATA[主页_车辆信息]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="60" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="17" >
<Disp><![CDATA[住友]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[进入车辆信息页成功]]></Obj>
<Details ><![CDATA[期望位置:您的位置：>> 车辆信息  实际位置:您的位置：>> 车辆信息]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:03]]></Time>
<TimeTick>1407922203</TimeTick>
<NodeArgs eType="User" icon="6" nRep="78" status="Passed" Source="Action1 [IntoVehiInfoFramePage]" SourceLine="28" >
<Disp><![CDATA[进入车辆信息页成功]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2014-8-13 - 17:30:01" eTime="2014-8-13 - 17:30:03" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="44" status="Passed" >
<Disp><![CDATA[Action1 [IntoVehiInfoFramePage] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T47">
<AName><![CDATA[Action1 [QueryMsgMaxReceivalID]]]></AName>
<Summary sTime="2014-8-13 - 17:30:03" eTime="2014-8-13 - 17:30:03" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="80" >
<Disp><![CDATA[Action1 [QueryMsgMaxReceivalID] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T48">
<AName><![CDATA[Action1 [InsertMsgQuerySource]]]></AName>
<Step rID="T49">
<Obj ><![CDATA[insert日志信息源码完毕]]></Obj>
<Details ><![CDATA[insert日志源码完毕]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:11]]></Time>
<TimeTick>1407922211</TimeTick>
<NodeArgs eType="User" icon="6" nRep="83" status="Passed" Source="Action1 [InsertMsgQuerySource]" SourceLine="94" >
<Disp><![CDATA[insert日志信息源码完毕]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2014-8-13 - 17:30:03" eTime="2014-8-13 - 17:30:12" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="82" status="Passed" >
<Disp><![CDATA[Action1 [InsertMsgQuerySource] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T50">
<AName><![CDATA[Action1 [Check_MsgQuery_Log]]]></AName>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[住友]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:13]]></Time>
<TimeTick>1407922213</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[主页_车辆信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:13]]></Time>
<TimeTick>1407922213</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[最新提交_.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:13]]></Time>
<TimeTick>1407922213</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="89" Source="Action1 [Check_MsgQuery_Log]" SourceLine="3" >
<Disp><![CDATA[最新提交_.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[最新提交_.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:13]]></Time>
<TimeTick>1407922213</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="92" Source="Action1 [Check_MsgQuery_Log]" SourceLine="4" >
<Disp><![CDATA[最新提交_.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[信息查询_.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:13]]></Time>
<TimeTick>1407922213</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="94" Source="Action1 [Check_MsgQuery_Log]" SourceLine="7" >
<Disp><![CDATA[信息查询_.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[信息查询_.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:13]]></Time>
<TimeTick>1407922213</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="97" Source="Action1 [Check_MsgQuery_Log]" SourceLine="8" >
<Disp><![CDATA[信息查询_.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[信息查询]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[您的位置>>车辆信息>>信息查询.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="100" Source="Action1 [Check_MsgQuery_Log]" SourceLine="12" >
<Disp><![CDATA[您的位置>>车辆信息>>信息查询.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="99" Source="Action1 [Check_MsgQuery_Log]" SourceLine="12" >
<Disp><![CDATA[信息查询]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="88" Source="Action1 [Check_MsgQuery_Log]" SourceLine="3" >
<Disp><![CDATA[主页_车辆信息]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="87" Source="Action1 [Check_MsgQuery_Log]" SourceLine="3" >
<Disp><![CDATA[住友]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[进入车辆信息-信息查询页成功]]></Obj>
<Details ><![CDATA[期望值：您的位置：>> 车辆信息 >>信息查询 实际值：您的位置：>> 车辆信息 >>信息查询 ]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<NodeArgs eType="User" icon="6" nRep="102" status="Passed" Source="Action1 [Check_MsgQuery_Log]" SourceLine="15" >
<Disp><![CDATA[进入车辆信息-信息查询页成功]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[住友]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[主页_车辆信息]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[信息查询]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[开始时间.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="107" Source="Action1 [Check_MsgQuery_Log]" SourceLine="23" >
<Disp><![CDATA[开始时间.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[开始时间.Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="108" Source="Action1 [Check_MsgQuery_Log]" SourceLine="24" >
<Disp><![CDATA[开始时间.Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[结束时间.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="111" Source="Action1 [Check_MsgQuery_Log]" SourceLine="26" >
<Disp><![CDATA[结束时间.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[结束时间.Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="112" Source="Action1 [Check_MsgQuery_Log]" SourceLine="27" >
<Disp><![CDATA[结束时间.Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[信息类型.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="115" Source="Action1 [Check_MsgQuery_Log]" SourceLine="29" >
<Disp><![CDATA[信息类型.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[信息类型.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["日志信息"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:14]]></Time>
<TimeTick>1407922214</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="118" Source="Action1 [Check_MsgQuery_Log]" SourceLine="30" >
<Disp><![CDATA[信息类型.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[查询.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:15]]></Time>
<TimeTick>1407922215</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="120" Source="Action1 [Check_MsgQuery_Log]" SourceLine="33" >
<Disp><![CDATA[查询.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[查询.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:30:15]]></Time>
<TimeTick>1407922215</TimeTick>