<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="QuickTest Professional" productVer="11.00" os="Windows XP" host="TY-GH"><DocLocation><![CDATA[C:\Program Files\HP\QuickTest Professional\Tests\Sumitomo\Script\Case4_1_VehiMsg_MsgQuery_Timing]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Case4_1_VehiMsg_MsgQuery_Timing]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Action1 [CleanHistoryData]]]></AName>
<Step rID="T6">
<Obj ><![CDATA[定时对应设备test历史数据清除完毕]]></Obj>
<Details ><![CDATA[定时对应设备test历史数据清除完毕]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:08]]></Time>
<TimeTick>1407920888</TimeTick>
<NodeArgs eType="User" icon="6" nRep="9" status="Passed" Source="Action1 [CleanHistoryData]" SourceLine="47" >
<Disp><![CDATA[定时对应设备test历史数据清除完毕]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2014-8-13 - 17:08:01" eTime="2014-8-13 - 17:08:08" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[Action1 [CleanHistoryData] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T7">
<AName><![CDATA[Action1 [Login]]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:14]]></Time>
<TimeTick>1407920894</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:14]]></Time>
<TimeTick>1407920894</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" status="Passed" Source="Action1 [Login]" SourceLine="5" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="14" status="Passed" Source="Action1 [Login]" SourceLine="5" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[住友]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[登录页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[帐户.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="19" Source="Action1 [Login]" SourceLine="7" >
<Disp><![CDATA[帐户.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="18" Source="Action1 [Login]" SourceLine="7" >
<Disp><![CDATA[登录页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="17" Source="Action1 [Login]" SourceLine="7" >
<Disp><![CDATA[住友]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;LockUnlockFlag&gt; column does not exist.<BR>Line (10): &quot;if(Datatable(&quot;LockUnlockFlag&quot;,&quot;Global&quot;)=&quot;锁车&quot;)then&quot;. ]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="20" status="Failed" Source="Action1 [Login]" SourceLine="9" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Account_2&gt; column does not exist.<BR>Line (11): &quot;Browser(&quot;住友&quot;).Page(&quot;登录页&quot;).WebEdit(&quot;帐户&quot;).Set Datatable(&quot;Account_2&quot;,&quot;Global&quot;)&quot;. ]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="21" status="Failed" Source="Action1 [Login]" SourceLine="10" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[住友]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[登录页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[帐户.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["test"]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" Source="Action1 [Login]" SourceLine="10" >
<Disp><![CDATA[帐户.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[密码.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="28" Source="Action1 [Login]" SourceLine="15" >
<Disp><![CDATA[密码.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[密码.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["123"]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="31" Source="Action1 [Login]" SourceLine="16" >
<Disp><![CDATA[密码.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[登录.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="33" Source="Action1 [Login]" SourceLine="18" >
<Disp><![CDATA[登录.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[登录.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:17]]></Time>
<TimeTick>1407920897</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="36" Source="Action1 [Login]" SourceLine="19" >
<Disp><![CDATA[登录.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="25" Source="Action1 [Login]" SourceLine="10" >
<Disp><![CDATA[登录页]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[主页]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:19]]></Time>
<TimeTick>1407920899</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[主页.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:19]]></Time>
<TimeTick>1407920899</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="40" Source="Action1 [Login]" SourceLine="22" >
<Disp><![CDATA[主页.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[HeadFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:22]]></Time>
<TimeTick>1407920902</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[登录用户名.GetROProperty "innertext"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:22]]></Time>
<TimeTick>1407920902</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="54" status="Warning" Source="Action1 [Login]" SourceLine="25" >
<Disp><![CDATA[登录用户名.GetROProperty "innertext"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[登录用户名]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "登录用户名" object's parent "HeadFrame" (class Frame). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:22]]></Time>
<TimeTick>1407920902</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[HeadFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Frame<br>|Url = http://192.168.30.173/sumitomo/web/top.aspx<br>Title = KOFACS<br>Name = head<br>]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:22]]></Time>
<TimeTick>1407920902</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="56" status="Warning" nType="Parent description" Source="Action1 [Login]" SourceLine="25" >
<Disp><![CDATA[HeadFrame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="14" nRep="55" status="Failed" nType="Run Error" Source="Action1 [Login]" SourceLine="25" >
<Disp><![CDATA[登录用户名]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:22]]></Time>
<TimeTick>1407920902</TimeTick>
<NodeArgs eType="General" icon="15" nRep="57" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="53" status="Failed" Source="Action1 [Login]" SourceLine="25" >
<Disp><![CDATA[HeadFrame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="39" status="Failed" Source="Action1 [Login]" SourceLine="22" >
<Disp><![CDATA[主页]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="24" status="Failed" Source="Action1 [Login]" SourceLine="10" >
<Disp><![CDATA[住友]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2014-8-13 - 17:08:08" eTime="2014-8-13 - 17:08:22" passed="1" failed="3" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="11" status="Failed" >
<Disp><![CDATA[Action1 [Login] Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:22]]></Time>
<TimeTick>1407920902</TimeTick>
<NodeArgs eType="General" icon="15" nRep="59" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2014-8-13 - 17:08:01" eTime="2014-8-13 - 17:08:22" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Case4_1_VehiMsg_MsgQuery_Timing Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[2014-8-13 - 17:08:22]]></Time>
<TimeTick>1407920902</TimeTick>
<NodeArgs eType="General" icon="16" nRep="62" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2014-8-13 - 17:08:00" eTime="2014-8-13 - 17:08:22" passed="2" failed="3" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Case4_1_VehiMsg_MsgQuery_Timing Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>